#+TITLE: Ben Harvey - Resume
#+EXPORT_FILE_NAME: Ben_Harvey-Resume
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+OPTIONS: author:nil
#+OPTIONS: date:nil
#+EXCLUDE_TAGS: noexport

Currently living and working in Newcastle NSW, Australia, I am a developer with a love for all things technology. I specialize as a full-stack engineer and have experience in developing solutions for both frontend and backend. My passion for innovative software solutions is supported by regular professional learning opportunities, undertaken in my personal time, which demonstrate I have a strong drive to stay at the forefront of web-based technologies. I am pragmatic in my approach to solving solutions and pride myself on finding simple solutions that fit the business need.
Having worked extensively in teams of software developers I am comfortable communicating over a range of mediums including; face to face, video and voice conference and text based applications. During my career I have worked with a range of multiple cross -functional teams and find I have a natural aptitude when collaborating on everything from project design phases to technical architecture and implementation.


* Skills
** Frontend

I am confident in leading teams with the design and implementation of projects using the following:

ReactJs
Typescript
HTML
CSS
Various testing frameworks
Mocha
Sinon
Jest


** Backend

I have demonstrated my robust experience in the following languages and frameworks:

NodeJS
Typescript
Express
C# .net framework / .NET core

** Infrastructure and DevOps

I have used AWS cloud services to deploy and run cloud native applications and have exemplary knowledge and understanding of the following:

Deploying applications using ECS
AWS Lamba and API gateway
Postgres
DynamoDB
S3
Lamba and serverless applications
General AWS deployments and networking

In addition to deploying applications to public clouds such as AWS I have an effective understanding of continuous deployment and integration practices. During my career, I have used multiple systems to implement build pipelines and feel confident in implementing these methodologies in any system or framework. The key products which I have utilized include:

Buildkite
Gitlab CI

To add to the skills listed above I have a strong interest in expanding my skill set and spend considerable time experimenting with new languages and frameworks. At present I am working with the following:

Golang (programming language)
Kubernetes (Container deployment tool)


* Career History

** January 2021 - Present, SwitchdIn

Web Services Engineer

Key responsibilities:

Part of a small team building web and mobile applications using Angular and Ionic. Working closely with our backend team to design and implement new features for the our main customer focused product.

** March 2020 - Present, Mudbath

Senior Software Developer

Key responsibilities:

Work with client requirements to design robust software systems
Write and review project documentation and designs
Implement code based on project requirements and brief
Mentor junior team members through code review and 1 on 1 coding sessions
Work as part of a cross functional team to meet client needs


** June 2019 - March 2020, nib Health Funds

Senior Software Developer

Key responsibilities:

Leading delivery teams in day to day functions
Mentoring of junior developers in:
Coding practice
System design and analysis
Work as part of cross functional team to develop software solutions for internal and external facing customers
Design technical solutions to meet business needs.
Undertake preparation tasks to scope and design solutions
Work with different business areas to ensure a cohesive approach to ensure design solutions meet requirements
Maintain applications as part of business-as-usual operations


** 2017 - June 2019, nib Health Funds

Full stack software developer

Key responsibilities:

Work as part of cross functional team to develop software solutions for internal and external facing customers
Design technical solutions to meet business needs.
Undertake preparation task to scope and design solutions
Work with different business areas to ensure a cohesive approach to ensure design solutions meet requirements
Maintain applications as part of business-as-usual operations


** 2016 - 2017, SwitchdIn

Software Developer

Key responsibilities:

Design and development of web platform frontend web stack (Postgres / Django / Nginx Angular JS on Amazon web services)
Planning for scaling web platform
Troubleshooting day to day issues
Working with customer feedback to improve the overall experience of the web platform

** 2015 - 2016, Forsythes Information Technology

Software developer

Key responsibilities:

Working as part of a scrum team to produce web based solutions for clients
Full stack development using Microsoft technologies
Creating and maintaining internal and customer facing documentation
Analysis of projects from high level through to task based detail
Planning, Creating and maintaining customer and internal server infrastructure
Creating and maintaining internal continuous delivery pipeline

** 2014 - 2015, Forsythes Information Technology

Level 1 Support Desk Engineer

Key responsibilities

Process and ticket management
Troubleshooting customer workstation and server issues
Troubleshooting customer network issues
Working as part of a larger team to maintain client infrastructure
Maintenance and improvement of internal and customer facing documentation


* Education

** 2011-2014. Newcastle University

Bachelor Information Technology
Major: Software Development and Applications

** 2009-2010. TAFE Hunter Institute.

Diploma of Surveying

** Hunter School Of Performing Arts

High School Certificate
